spring:
    application:
        name: sjzcjx_boot
    profiles:
        include: props
    datasource:
        url: ${spring.datasource.url}
        driver-class-name: ${spring.datasource.driver-class-name}
        username: ${spring.datasource.username}
        password: ${spring.datasource.password}
server:
    port: 8080
mybatis:
    mapper-locations: classpath:mapper/*xml
    type-aliases-package: cn.sjzcjx.sjzcjx_boot.mybatis.entity


